baseURL = ""
disqusShortname = ""
languageCode = "en-uk"
paginate = "5"
summaryLength = "10"
theme = "sawmill"
title = "Wellington Frothers FC"
[Author]
    name = "Chris Chester"
[Params]
    logo = "images/logo.png"
[Params.BrandColor]
    normal = "#33A5FF"
    light = "#A4D7FF"
    dark = "#0C5085"
    shadow = "#476073"
